version: '3.1'

services: 
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/fitnessdb.sql:/docker-entrypoint-initdb.d/fitnessdb.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fitnessdb
  fitness-spring:
    build: .
    container_name: fitness-spring-container
    restart: always
    depends_on: 
      - mysql
    ports: 
      - 8080:3000
